### PR TITLE
Oc with secureboot enabled

### PR DESCRIPTION
**Pull request by Xiashangning**
With this method, one can enable the MS secure boot option in UEFI BIOS and be able to boot OC as well

### CODE REVIEW

**Comment by badstorm** [comment]
Ok, can you explain the process you introduce? 

If I understand correclty you first load grub efi, then grub load opencore and then opecore load macos, right? 

Where is located the grug.cfg? 
Why you also keep x86 grub files?

**Comment by Xiashangning** [comment]
The process is just as you described. grub loads grubx64_real.efi automatically, and in fact grubx64_real.efi is the copy of OC's bootx64.efi. I renamed it to grubx64_real.efi for grub to load it.

**Comment by Xiashangning** [comment]
The grub files are for signing the certificate required by the firmware, after signing, maybe you can delete that folder? You ca have a try and tell me whether you can still boot OC.

**Comment by badstorm** [comment]
I tryied your configuration with grub but it dosen't work.



Any ideas?

**Comment by Xiashangning** [comment]
then you need to sign it yourself, rename grubx64_real.efi to sth else and rename grubx64_real_bak.efi to grubx64_real.efi then boot it and sign the certificate.

**Comment by Xiashangning** [comment]
Sry, Is there a OK button at the middle of this photo?

**Comment by Xiashangning** [comment]
This is the procedure 

Credit: https://www.bugprogrammer.me/2019/07/06/clover-with-secure-boot.html

**Comment by badstorm** [comment]
Ok, cert must be imported manually

**Comment by badstorm** [comment]
Since this solution is a little tricky, I think is not so good to add as default configuration, but i created ad dedicated readme for this workaround. Feel free to correct it and send a PR with the edits. ;) 

https://github.com/badstorm/surface-pro-7-opencore/blob/master/SecureBoot.With.Grub.md

Thanks for your support!

**Pull request closed without merging**
