### PR TITLE
Update config.plist

### PR DESCRIPTION
**Pull request by jackjack1-su**
Enabled the SetupVirtualMap
And enabled the AppleSmclo for VirtualSMC (Same as VirtualSMC.efi)

### CODE REVIEW

**Comment by badstorm** [comment]
In my case if I enabled SetupVirtualMap macos not boot (no progress bar). Did you never had this problem?

For the other option, if enabled we can remove virtualsmv.efi?

**Comment by jackjack1-su** [comment]
> In my case if I enabled SetupVirtualMap macos not boot (no progress bar). Did you never had this problem?
> 
> For the other option, if enabled we can remove virtualsmv.efi?

Hmmm...That's really weird.I'll keep searching some cases so that I can sure the SetupVirtualMap Quirk.
And the VirtualSMC.efi can be removed.

**Comment by badstorm** [comment]
Ok, `SetupVirtualMap` now works also on my Surface so I added it to last release. But I tried to remove `VirtualSMC` and add `AppleSmclo` but stuck on os loader (the progress stops in the middle). 
Can you try with the last build?

For the moment i left  `VirtualSMC` without adding `AppleSmclo` option

**Comment by jackjack1-su** [comment]
OK Well... But Now I'm using OC 0.6.9. And AppleSmclo works perfect on my SP7...
However it's not necessary LOL

**Comment by jackjack1-su** [comment]
But I still want to ask that have you updated your firmware?

**Comment by jackjack1-su** [comment]
I've updated so I think this is important D:

**Pull request closed without merging**
