### PR TITLE
Fixed UEFI issue and some ameliorations

### PR DESCRIPTION
**Pull request by Xiashangning**
OpenCore 0.6.7 master version to fix the UEFI issue brought by firmware update.
Added several SSDTs
Checked through config.plist and removed all the unnecessary configurations.
Use self-made AppleALC instead of VoodooHDA for better performance, increased speaker volume for example.
One can enable Audio Support simply by enabling the 'Audio Support' option in UEFI/Audio section.
Support Big Sur 11.2.

### CODE REVIEW

**Comment by badstorm** [comment]
Thanks, ok i'll wait for the release of OC 0.67 to update the repo.
Here you also update all the kext (like Lilu)? You edited with custom info one of them?
What do you means with "self-made AppleALC", what do you change from the original? In this case I think we need to fork the original repo and keep it updated with your edits.

**Comment by Xiashangning** [comment]
The original AppleALC has no usable layout for SP7 so I have made one.
No, i do not edit the other kexts, I just updated them to the latest release version

**Comment by badstorm** [comment]
Why you added all this `aml `files? Can you explain me oneby one what improves add?

Abount kexts: for `CPUFriend` and `CPUFriendDataProvider` you use a ready one or you make a custom one? Why you add `NVMeFix.kext` and `USBInjectAll.kext`?

**Comment by Xiashangning** [comment]
The aml files are based on OC-little, I added some devices that are missed on SP7 while presented on macOS (most is just as I said, ameliorations, perhaps stability improvement?) You can see that I removed two of your unnecessary aml files, they have no use for SP7.
Maybe CPUFriend is not needed, I made a custom one based on the official instruction to generate a CPUFriendDataProvider. NVMeFix is for better power management and trim capability. USBInjectAll is because my custom one does not work on other SP7s, I believe we have to make our own USBPorts after installation.

**Comment by badstorm** [comment]
Ok, my intent is to make the more clear configuration without unneccesary files. So I'll check the aml you remove and if not used i'll remove too. If the other you added are not used on SP7 for the moment i'don't add them. If we verify that one of them improve a particolar aspect i'll definitely add it.

CPUFriend I know is used for better power management and if you create a custom data file and you observe an improvement i can add it.

Ok for NVMeFix,

I don't understand why you add USBInjectAll. In my acutal configuration usb works perfect, also with adapters. Did you have troubles with usb?

**Comment by jackjack1-su** [comment]
Plz use DeviceProperties to apply WEG fixes and AppleALC inject. 
The boot-args are just used for debug instead of daily use.
And if the "PollAppleHotKeys" is on, the UEFI-Input-KeySwap should be enabled. Or the option key won't work on boot. (Such as boot-selector).

**Comment by jackjack1-su** [comment]
> The aml files are based on OC-little, I added some devices that are missed on SP7 while presented on macOS (most is just as I said, ameliorations, perhaps stability improvement?) You can see that I removed two of your unnecessary aml files, they have no use for SP7.
> Maybe CPUFriend is not needed, I made a custom one based on the official instruction to generate a CPUFriendDataProvider. NVMeFix is for better power management and trim capability. USBInjectAll is because my custom one does not work on other SP7s, I believe we have to make our own USBPorts after installation.

The USB doesn't work because you have changed the SMBIOS to the MacBookAir9,1 and the USBPorts has a MacBookPro SMBIOS. (The USBPorts checks the SMBIOS to avoid the unexpected inject?)

**Comment by jackjack1-su** [comment]
> Ok, my intent is to make the more clear configuration without unneccesary files. So I'll check the aml you remove and if not used i'll remove too. If the other you added are not used on SP7 for the moment i'don't add them. If we verify that one of them improve a particolar aspect i'll definitely add it.
> 
> CPUFriend I know is used for better power management and if you create a custom data file and you observe an improvement i can add it.
> 
> Ok for NVMeFix,
> 
> I don't understand why you add USBInjectAll. In my acutal configuration usb works perfect, also with adapters. Did you have troubles with usb?

Reason for the USBInjectAll is because the SMBIOS is changed into the MacBookAir9,1 and the USBPorts has a MacBookPro SMBIOS. (The USBPorts checks the SMBIOS to avoid the unexpected inject?)
And the reason of the SMBIOS changes: The MacBookAir SMBIOS brings more stable iGPU(Can decrease the EL[0] KP probability)

**Pull request closed without merging**
